### ISSUE TITLE
Notebook random_forest/random_forest_regression.ipynb seems broken

### ISSUE THREAD

**Issue by rjghendrikx** [complexity-science-hub/ranking_npis#2]
Hi,

When executing Cell 6 of the random_forest_regression.ipynb notebook in folder random_forest, I'm getting the following error.

```
In [6]: rfa.crossvalidate(n_processes=30)

(1, 1, 0.01)
---------------------------------------------------------------------------
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/python3/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/anaconda3/envs/python3/lib/python3.9/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/Users/ruudhendrikx/Documents/Projects/covid/ranking_npis/random_forest/randomforestanalysis.py", line 48, in compute_performance_metrics
    X_test = X.loc[(countries[test_index]),:]
  File "/usr/local/anaconda3/envs/python3/lib/python3.9/site-packages/pandas/core/indexing.py", line 888, in __getitem__
    return self._getitem_tuple(key)
  File "/usr/local/anaconda3/envs/python3/lib/python3.9/site-packages/pandas/core/indexing.py", line 1059, in _getitem_tuple
    return self._getitem_lowerdim(tup)
  File "/usr/local/anaconda3/envs/python3/lib/python3.9/site-packages/pandas/core/indexing.py", line 790, in _getitem_lowerdim
    return self._getitem_nested_tuple(tup)
  File "/usr/local/anaconda3/envs/python3/lib/python3.9/site-packages/pandas/core/indexing.py", line 864, in _getitem_nested_tuple
    obj = getattr(obj, self.name)._getitem_axis(key, axis=axis)
  File "/usr/local/anaconda3/envs/python3/lib/python3.9/site-packages/pandas/core/indexing.py", line 1112, in _getitem_axis
    return self._getitem_iterable(key, axis=axis)
  File "/usr/local/anaconda3/envs/python3/lib/python3.9/site-packages/pandas/core/indexing.py", line 1052, in _getitem_iterable
    keyarr, indexer = self._get_listlike_indexer(key, axis, raise_missing=False)
  File "/usr/local/anaconda3/envs/python3/lib/python3.9/site-packages/pandas/core/indexing.py", line 1253, in _get_listlike_indexer
    indexer, keyarr = ax._convert_listlike_indexer(key)
  File "/usr/local/anaconda3/envs/python3/lib/python3.9/site-packages/pandas/core/indexes/multi.py", line 2566, in _convert_listlike_indexer
    raise KeyError(f"{keyarr[mask]} not in index")
KeyError: "['Liechtenstein'] not in index"
"""

The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
<ipython-input-6-94a944329ac2> in <module>
----> 1 rfa.crossvalidate(n_processes=30)

~/Documents/Projects/covid/ranking_npis/random_forest/randomforestanalysis.py in crossvalidate(self, **kwargs)
    229 
    230             pool = mp.Pool(processes=n_processes)
--> 231             newres = pool.starmap(compute_performance_metrics,args)
    232             pool.close()
    233             pool.join()

/usr/local/anaconda3/envs/python3/lib/python3.9/multiprocessing/pool.py in starmap(self, func, iterable, chunksize)
    370         `func` and (a, b) becomes func(a, b).
    371         '''
--> 372         return self._map_async(func, iterable, starmapstar, chunksize).get()
    373 
    374     def starmap_async(self, func, iterable, chunksize=None, callback=None,

/usr/local/anaconda3/envs/python3/lib/python3.9/multiprocessing/pool.py in get(self, timeout)
    769             return self._value
    770         else:
--> 771             raise self._value
    772 
    773     def _set(self, i, obj):

KeyError: "['Liechtenstein'] not in index"

```

Is this a bug or am I not using the correct environment.

A suggestions from my side would be to add a requirements.txt containing the specific environment in which this code is successfully executing.

Best Regards,

Ruud

**Comment by rjghendrikx** [comment]
On another machine I'm getting a similar error with the same line of code:

```
In [6]: rfa.crossvalidate(n_processes=30)

(1, 1, 0.01)
---------------------------------------------------------------------------
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/anaconda3/lib/python3.7/multiprocessing/pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/Users/ruudhendrikx/Documents/Projects/covid/ranking_npis/random_forest/randomforestanalysis.py", line 36, in compute_performance_metrics
    X,y = shift_outcome(X,y,s,shift_date="y")
  File "/Users/ruudhendrikx/Documents/Projects/covid/ranking_npis/random_forest/randomforestanalysis.py", line 106, in shift_outcome
    y_shifted.drop(y_shifted.loc[np.isnan(y_shifted.values)].index,inplace=True)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py", line 1500, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py", line 1869, in _getitem_axis
    return self._getbool_axis(key, axis=axis)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py", line 1516, in _getbool_axis
    inds, = key.nonzero()
ValueError: too many values to unpack (expected 1)
"""

The above exception was the direct cause of the following exception:

ValueError                                Traceback (most recent call last)
<ipython-input-6-94a944329ac2> in <module>
----> 1 rfa.crossvalidate(n_processes=30)

~/Documents/Projects/covid/ranking_npis/random_forest/randomforestanalysis.py in crossvalidate(self, **kwargs)
    229 
    230             pool = mp.Pool(processes=n_processes)
--> 231             newres = pool.starmap(compute_performance_metrics,args)
    232             pool.close()
    233             pool.join()

/usr/local/anaconda3/lib/python3.7/multiprocessing/pool.py in starmap(self, func, iterable, chunksize)
    274         `func` and (a, b) becomes func(a, b).
    275         '''
--> 276         return self._map_async(func, iterable, starmapstar, chunksize).get()
    277 
    278     def starmap_async(self, func, iterable, chunksize=None, callback=None,

/usr/local/anaconda3/lib/python3.7/multiprocessing/pool.py in get(self, timeout)
    655             return self._value
    656         else:
--> 657             raise self._value
    658 
    659     def _set(self, i, obj):

ValueError: too many values to unpack (expected 1)
```

Thanks in advance.
